add: save user account details for manage staff use case
Issues:
1. cannot think of a way to save more than a single role, if we want to assign more than 1 role to this new employee, with current model. Thought of changing the model for User to include an attribute List<RoleEnum> roles. Dk if recommended.

2. cannot save user

3. create-new-user-account-form.html throws error, which is wierd since isEditMode is boolean

 Error: Caused by: org.thymeleaf.exceptions TemplateProcessingException: Exception evaluating SpringEL expression: "!isEditMode"
 (template: "admin/manage-staff/create-new-user-account-form" - line 84, col 10)

 Caused by: org.springframework.expression.spel.SpelEvaluationException: EL1001E: Type conversion problem, cannot convert from null to boolean